# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.zip'
    destinationFolder: 'ProtractorPackage'
    cleanDestinationFolder: true

- task: Npm@1
  inputs:
      command: 'install'
      workingDir: 'ProtractorPackage/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests'

- task: CmdLine@2
  inputs:
    script: 'node_modules/protractor/bin/webdriver-manager update'
    workingDirectory: 'ProtractorPackage/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests'

- task: CmdLine@2
  inputs:
      script: 'node_modules/protractor/bin/protractor e2e/protractor.conf.js'
      workingDirectory: 'ProtractorPackage/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'xmlresults.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/ProtractorPackage/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests/testResults/$(time)/'


