# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'cypress1.zip'
    destinationFolder: 'cypress'
    cleanDestinationFolder: true

- task: CmdLine@2
  inputs:
    script: 'dir'
    workingDirectory: 'cypress'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'cypress/cypress'

- task: CmdLine@2
  inputs:
    script: 'npm install cypress --save'
    workingDirectory: 'cypress/cypress'

- task: CmdLine@2
  inputs:
    script: 'dir'
    workingDirectory: 'cypress/cypress/cypress/integration/examples'

    
- task: CmdLine@2
  inputs:
    script: 'npx cypress run --browser chrome --spec "cypress/cypress/cypress/integration/examples/*.js"'
    workingDirectory: 'cypress/cypress'