# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.zip'
    destinationFolder: 'ProtractorPackage2'
    cleanDestinationFolder: true

- task: Npm@1
  inputs:
      command: 'install'
      workingDir: 'ProtractorPackage2/ProtractorEndToEndTest-master2/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'ProtractorPackage2/ProtractorEndToEndTest-master2/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests'
    customCommand: 'webdriver-manager'


- task: CmdLine@2
  inputs:
    script: 'node webdriver-manager update --ignore_ssl --proxy'
    workingDirectory: 'ProtractorPackage2/ProtractorEndToEndTest-master2/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests/node_modules/protractor/bin'


- task: CmdLine@2
  inputs:
    script: 'npm install -g protractor && npm start'
    workingDirectory: 'ProtractorPackage2/ProtractorEndToEndTest-master2/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests/node_modules/protractor/bin'

- task: CmdLine@2
  inputs:
    script: 'ng e2e --no-serve'
    workingDirectory: 'ProtractorPackage2/ProtractorEndToEndTest-master2/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests/node_modules/protractor/bin'

- task: CmdLine@2
  inputs:
      script: "npm run protractor protractor.conf.js'"
      workingDirectory: 'ProtractorPackage2/ProtractorEndToEndTest-master2/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests/e2e/'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'xmlresults.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/ProtractorEndToEndTest-master2/ProtractorEndToEndTest-master/EndToEndTests/EndToEndTests/testResults/$(time)/'


